name: Update GitHub Stats

on:
  schedule:
    - cron: '47 2 * * *'  # Runs daily at 02:47 UTC
  workflow_dispatch:  

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install axios chalk --no-save

      - name: Fetch GitHub Stats and Generate SVG
        run: node src/update-stats.js ${{ github.repository_owner }}

      - name: Update Template with Hacker Theme
        run: |
          node updater.js ${{ github.repository_owner }} hacker

      - name: Commit and Push Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add github_stats.svg
          git commit -m "Updated GitHub Stats 🤩 (Hacker Theme)" || echo "No changes to commit"
          git push https://${{ secrets.GHT }}@github.com/${{ github.repository }} github-stats


