name: Update GitHub Stats

on:
  schedule:
    - cron: '47 2 * * *' 
  workflow_dispatch:  

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install axios chalk

      - name: Fetch GitHub Stats and Generate SVG
        run: |
          node -e "
          const fs = require('fs');
          const axios = require('axios');
          axios.get('https://api.github.com/users/${{ github.repository_owner }}')
            .then(response => {
              const stats = response.data;
              const svgContent = \`<svg width='500' height='200' xmlns='http://www.w3.org/2000/svg'>
                <rect width='100%' height='100%' fill='black'/>
                <text x='20' y='40' fill='white' font-size='20'>GitHub Stats for ${stats.login}</text>
                <text x='20' y='80' fill='white' font-size='16'>Public Repos: ${stats.public_repos}</text>
                <text x='20' y='110' fill='white' font-size='16'>Followers: ${stats.followers}</text>
                <text x='20' y='140' fill='white' font-size='16'>Following: ${stats.following}</text>
                </svg>\`;
              fs.writeFileSync('github_stats.svg', svgContent);
            });
          "

      - name: Commit and Push Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add github_stats.svg
          git commit -m "Updated GitHub Stats 🤩"
          git push origin github-stats
